-- =====================================================
-- SCRIPT DE SIMULAÇÃO: 10 COTAÇÕES DE EXEMPLO
-- Execute este script no SQL Editor do Supabase
-- =====================================================

-- IMPORTANTE: Todas as cotações serão criadas para a organização do fornecedor
-- Organization ID: 81463c26-2b9d-4b59-8a32-90bbcaff00d5

-- Inserir 10 cotações de exemplo (todas para sua organização)
INSERT INTO quotes (
  id,
  organization_id,
  pedido_id,
  titulo,
  solicitante,
  contato,
  carater_internacao,
  encerramento_cotacao,
  forma_pagamento,
  etapa,
  patient_name,
  surgery_date,
  surgery_location,
  operadora,
  senha_autorizacao,
  atendimento,
  agenda,
  medico,
  crm_uf,
  status,
  procedures,
  products,
  non_coded_products,
  documents,
  pre_surgical_files,
  observacao_comprador,
  source_platform,
  external_quote_id
) VALUES
  -- Cotação 1: Artroplastia de Joelho
  (
    'c0000001-0000-0000-0000-000000000001',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-001',
    'Artroplastia Total de Joelho',
    'Dr. Roberto Silva',
    'roberto.silva@saolucas.com.br',
    'Eletivo',
    NOW() + INTERVAL '48 hours',
    'Faturamento',
    'Aguardando Cotação',
    'João da Silva',
    (NOW() + INTERVAL '7 days')::text,
    'Centro Cirúrgico 2',
    'Unimed',
    'AUTH-12345',
    'Internação',
    'Agenda Ortopedia',
    'Dr. Carlos Mendes',
    'CRM/SP 123456',
    'pending',
    '[{"codigo": "TUSS-30715016", "descricao": "Artroplastia Total de Joelho"}]'::jsonb,
    '[
      {"referencia": "PROT-JOELHO-001", "name": "Prótese de Joelho Total Cimentada", "quantity": 1},
      {"referencia": "PARAF-ORTOP-001", "name": "Parafusos de Fixação 4.5mm", "quantity": 4},
      {"referencia": "CIMENTO-001", "name": "Cimento Ósseo 40g", "quantity": 2}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Paciente com histórico de artrose avançada. Preferência por prótese de marca reconhecida.',
    'OPMEnexo',
    'OPME-2026-001'
  ),

  -- Cotação 2: Cirurgia Cardíaca
  (
    'c0000002-0000-0000-0000-000000000002',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-002',
    'Implante de Stent Coronariano',
    'Dra. Ana Paula',
    'ana.paula@cardiacopremium.com.br',
    'Urgência',
    NOW() + INTERVAL '24 hours',
    'Particular',
    'Aguardando Cotação',
    'Maria Santos',
    (NOW() + INTERVAL '2 days')::text,
    'Hemodinâmica',
    'Bradesco Saúde',
    'AUTH-67890',
    'Internação',
    'Agenda Cardiologia',
    'Dr. Fernando Costa',
    'CRM/SP 234567',
    'pending',
    '[{"codigo": "TUSS-30601017", "descricao": "Angioplastia Coronariana"}]'::jsonb,
    '[
      {"referencia": "STENT-CARD-001", "name": "Stent Farmacológico 3.0x18mm", "quantity": 2},
      {"referencia": "CATETER-001", "name": "Cateter Guia 6F", "quantity": 1},
      {"referencia": "BALAO-001", "name": "Balão de Angioplastia 3.0x15mm", "quantity": 1}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'URGENTE: Paciente com IAM. Necessário entrega em até 24h.',
    'OPMEnexo',
    'OPME-2026-002'
  ),

  -- Cotação 3: Cirurgia de Coluna
  (
    'c0000003-0000-0000-0000-000000000003',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-003',
    'Artrodese Lombar L4-L5',
    'Dr. Paulo Martins',
    'paulo.martins@ortopedicavida.com.br',
    'Eletivo',
    NOW() + INTERVAL '72 hours',
    'Faturamento',
    'Aguardando Cotação',
    'Pedro Oliveira',
    (NOW() + INTERVAL '10 days')::text,
    'Centro Cirúrgico 1',
    'Amil',
    'AUTH-11223',
    'Internação',
    'Agenda Coluna',
    'Dr. Ricardo Alves',
    'CRM/SP 345678',
    'pending',
    '[{"codigo": "TUSS-30715068", "descricao": "Artrodese Vertebral"}]'::jsonb,
    '[
      {"referencia": "CAGE-LOMBAR-001", "name": "Cage Intersomático PEEK", "quantity": 2},
      {"referencia": "PARAF-PEDIC-001", "name": "Parafusos Pediculares 6.5mm", "quantity": 4},
      {"referencia": "HASTE-TITAN-001", "name": "Hastes de Titânio 5.5mm", "quantity": 2},
      {"referencia": "ENXERTO-001", "name": "Enxerto Ósseo Sintético", "quantity": 1}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Paciente com hérnia de disco e estenose. Preferência por materiais de titânio.',
    'OPMEnexo',
    'OPME-2026-003'
  ),

  -- Cotação 4: Prótese de Quadril
  (
    'c0000004-0000-0000-0000-000000000004',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-004',
    'Artroplastia Total de Quadril',
    'Dr. Roberto Silva',
    'roberto.silva@saolucas.com.br',
    'Eletivo',
    NOW() + INTERVAL '96 hours',
    'Faturamento',
    'Aguardando Cotação',
    'Ana Costa',
    (NOW() + INTERVAL '14 days')::text,
    'Centro Cirúrgico 3',
    'SulAmérica',
    'AUTH-44556',
    'Internação',
    'Agenda Ortopedia',
    'Dr. Carlos Mendes',
    'CRM/SP 123456',
    'pending',
    '[{"codigo": "TUSS-30715024", "descricao": "Artroplastia Total de Quadril"}]'::jsonb,
    '[
      {"referencia": "PROT-QUADRIL-001", "name": "Prótese de Quadril Não Cimentada", "quantity": 1},
      {"referencia": "CABECA-CERAM-001", "name": "Cabeça Femoral Cerâmica 32mm", "quantity": 1},
      {"referencia": "ACETABULO-001", "name": "Componente Acetabular 54mm", "quantity": 1}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Paciente jovem (45 anos). Preferência por prótese não cimentada com cabeça cerâmica.',
    'OPMEnexo',
    'OPME-2026-004'
  ),

  -- Cotação 5: Marca-passo Cardíaco
  (
    'c0000005-0000-0000-0000-000000000005',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-005',
    'Implante de Marca-passo Dupla Câmara',
    'Dra. Ana Paula',
    'ana.paula@cardiacopremium.com.br',
    'Urgência',
    NOW() + INTERVAL '36 hours',
    'Faturamento',
    'Aguardando Cotação',
    'José Ferreira',
    (NOW() + INTERVAL '3 days')::text,
    'Sala de Eletrofisiologia',
    'Porto Seguro',
    'AUTH-77889',
    'Internação',
    'Agenda Arritmia',
    'Dr. Fernando Costa',
    'CRM/SP 234567',
    'pending',
    '[{"codigo": "TUSS-30601033", "descricao": "Implante de Marca-passo"}]'::jsonb,
    '[
      {"referencia": "MP-DUPLA-001", "name": "Marca-passo Dupla Câmara", "quantity": 1},
      {"referencia": "ELETRODO-VD-001", "name": "Eletrodo Ventricular Direito", "quantity": 1},
      {"referencia": "ELETRODO-AD-001", "name": "Eletrodo Atrial Direito", "quantity": 1}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Paciente com bloqueio AV total. Necessário marca-passo com bateria de longa duração.',
    'OPMEnexo',
    'OPME-2026-005'
  ),

  -- Cotação 6: Artroscopia de Ombro
  (
    'c0000006-0000-0000-0000-000000000006',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-006',
    'Reparo de Manguito Rotador',
    'Dr. Paulo Martins',
    'paulo.martins@ortopedicavida.com.br',
    'Eletivo',
    NOW() + INTERVAL '120 hours',
    'Faturamento',
    'Aguardando Cotação',
    'Carlos Alberto',
    (NOW() + INTERVAL '15 days')::text,
    'Centro Cirúrgico 2',
    'Unimed',
    'AUTH-99001',
    'Ambulatorial',
    'Agenda Ombro',
    'Dr. Ricardo Alves',
    'CRM/SP 345678',
    'pending',
    '[{"codigo": "TUSS-30715092", "descricao": "Reparo Artroscópico do Manguito Rotador"}]'::jsonb,
    '[
      {"referencia": "ANCORA-OMBRO-001", "name": "Âncoras de Sutura 5.5mm", "quantity": 3},
      {"referencia": "FIO-SUTURA-001", "name": "Fio de Sutura de Alta Resistência", "quantity": 2},
      {"referencia": "LAMINA-ARTRO-001", "name": "Lâmina de Shaver 4.0mm", "quantity": 1}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Lesão completa do supraespinal. Preferência por âncoras bioabsorvíveis.',
    'OPMEnexo',
    'OPME-2026-006'
  ),

  -- Cotação 7: Prótese de Mama
  (
    'c0000007-0000-0000-0000-000000000007',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-007',
    'Reconstrução Mamária Bilateral',
    'Dra. Juliana Reis',
    'juliana.reis@santamaria.com.br',
    'Eletivo',
    NOW() + INTERVAL '168 hours',
    'Particular',
    'Aguardando Cotação',
    'Fernanda Lima',
    (NOW() + INTERVAL '21 days')::text,
    'Centro Cirúrgico 4',
    'Particular',
    NULL,
    'Internação',
    'Agenda Plástica',
    'Dra. Patricia Souza',
    'CRM/RJ 456789',
    'pending',
    '[{"codigo": "TUSS-30701070", "descricao": "Reconstrução Mamária"}]'::jsonb,
    '[
      {"referencia": "PROT-MAMA-001", "name": "Prótese de Silicone 300cc Perfil Alto", "quantity": 2},
      {"referencia": "TELA-CIRURG-001", "name": "Tela Cirúrgica Absorvível", "quantity": 1}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Reconstrução pós-mastectomia. Paciente solicita próteses de marca premium.',
    'OPMEnexo',
    'OPME-2026-007'
  ),

  -- Cotação 8: Cirurgia de Catarata
  (
    'c0000008-0000-0000-0000-000000000008',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-008',
    'Facoemulsificação com Implante de LIO',
    'Dr. Marcos Vieira',
    'marcos.vieira@saolucas.com.br',
    'Eletivo',
    NOW() + INTERVAL '144 hours',
    'Faturamento',
    'Aguardando Cotação',
    'Helena Martins',
    (NOW() + INTERVAL '18 days')::text,
    'Centro Cirúrgico Oftalmológico',
    'Bradesco Saúde',
    'AUTH-22334',
    'Ambulatorial',
    'Agenda Oftalmologia',
    'Dr. Eduardo Pinto',
    'CRM/SP 567890',
    'pending',
    '[{"codigo": "TUSS-30803015", "descricao": "Facoemulsificação"}]'::jsonb,
    '[
      {"referencia": "LIO-MONO-001", "name": "Lente Intraocular Monofocal +22.0D", "quantity": 1},
      {"referencia": "VISCOELAS-001", "name": "Viscoelástico 1ml", "quantity": 1}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Catarata madura. Paciente solicita lente de boa qualidade óptica.',
    'OPMEnexo',
    'OPME-2026-008'
  ),

  -- Cotação 9: Hérnia de Disco
  (
    'c0000009-0000-0000-0000-000000000009',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-009',
    'Discectomia Cervical C5-C6',
    'Dr. Paulo Martins',
    'paulo.martins@ortopedicavida.com.br',
    'Eletivo',
    NOW() + INTERVAL '192 hours',
    'Faturamento',
    'Aguardando Cotação',
    'Roberto Almeida',
    (NOW() + INTERVAL '25 days')::text,
    'Centro Cirúrgico 1',
    'Amil',
    'AUTH-55667',
    'Internação',
    'Agenda Coluna',
    'Dr. Ricardo Alves',
    'CRM/SP 345678',
    'pending',
    '[{"codigo": "TUSS-30715076", "descricao": "Discectomia Cervical"}]'::jsonb,
    '[
      {"referencia": "CAGE-CERV-001", "name": "Cage Cervical PEEK", "quantity": 1},
      {"referencia": "PLACA-CERV-001", "name": "Placa Cervical Anterior", "quantity": 1},
      {"referencia": "PARAF-CERV-001", "name": "Parafusos Cervicais 4.0mm", "quantity": 4}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Hérnia discal com compressão radicular. Preferência por cage com placa integrada.',
    'OPMEnexo',
    'OPME-2026-009'
  ),

  -- Cotação 10: Prótese de Tornozelo
  (
    'c0000010-0000-0000-0000-000000000010',
    '81463c26-2b9d-4b59-8a32-90bbcaff00d5',
    'PED-2026-010',
    'Artroplastia Total de Tornozelo',
    'Dra. Juliana Reis',
    'juliana.reis@santamaria.com.br',
    'Eletivo',
    NOW() + INTERVAL '216 hours',
    'Faturamento',
    'Aguardando Cotação',
    'Marcos Silva',
    (NOW() + INTERVAL '30 days')::text,
    'Centro Cirúrgico 2',
    'SulAmérica',
    'AUTH-88990',
    'Internação',
    'Agenda Ortopedia',
    'Dr. André Santos',
    'CRM/RJ 678901',
    'pending',
    '[{"codigo": "TUSS-30715032", "descricao": "Artroplastia de Tornozelo"}]'::jsonb,
    '[
      {"referencia": "PROT-TORN-001", "name": "Prótese de Tornozelo Total", "quantity": 1},
      {"referencia": "PARAF-TORN-001", "name": "Parafusos de Fixação 3.5mm", "quantity": 6}
    ]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'Artrose pós-traumática severa. Paciente atleta, necessita prótese de alta performance.',
    'OPMEnexo',
    'OPME-2026-010'
  )
ON CONFLICT (id) DO NOTHING;

-- Verificar cotações criadas
SELECT 
  pedido_id,
  titulo,
  patient_name,
  status,
  encerramento_cotacao,
  jsonb_array_length(products) as num_produtos
FROM quotes
ORDER BY created_at DESC
LIMIT 10;
